version: '3.1'

services:
  billete_backend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - billete_pg
      - billete_redis
    environment:
      NODE_ENV: production
  billete_pg:
    image: postgres:15.1
    container_name: billete_pg
    restart: always
    environment:
      POSTGRES_DB: billete
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - billete
  billete_redis:
    image: redis:alpine
    container_name: billete_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - billete
networks:
  billete:
    driver: bridge
